import { NextResponse } from "next/server";
import { upsertChatgptWebSession } from "@/lib/localDb";
import {
  normalizeChatgptWebCaptureBundle,
  redactChatgptWebSession,
  validateAndStoreChatgptWebSession,
} from "@/lib/chatgptWeb";
import { clearServerCache } from "@/lib/serverCache";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, X-Web-Connect-Token",
};

/* one-time tokens generated by the dashboard — live for 5 min */
const pendingTokens = new Map();

export function createWebConnectToken() {
  const token = crypto.randomUUID();
  pendingTokens.set(token, Date.now() + 5 * 60_000);
  /* auto-purge expired */
  for (const [k, exp] of pendingTokens) {
    if (Date.now() > exp) pendingTokens.delete(k);
  }
  return token;
}

function consumeToken(token) {
  const exp = pendingTokens.get(token);
  if (!exp || Date.now() > exp) return false;
  pendingTokens.delete(token);
  return true;
}

export async function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: CORS_HEADERS });
}

export async function POST(request) {
  const token = request.headers.get("x-web-connect-token") || "";
  if (!consumeToken(token)) {
    return NextResponse.json(
      { error: "Invalid or expired web-connect token" },
      { status: 403, headers: CORS_HEADERS },
    );
  }

  try {
    const payload = await request.json();
    const normalized = normalizeChatgptWebCaptureBundle(payload);
    await upsertChatgptWebSession(normalized);
    clearServerCache();

    const session = await validateAndStoreChatgptWebSession();
    clearServerCache();

    return NextResponse.json(
      { ok: true, session: redactChatgptWebSession(session) },
      { status: 200, headers: CORS_HEADERS },
    );
  } catch (error) {
    return NextResponse.json(
      { error: error.message || "Web connect failed" },
      { status: 400, headers: CORS_HEADERS },
    );
  }
}
